# version: '3.8'

# services:
#   # PostgreSQL Database
#   postgres:
#     image: postgres:15
#     container_name: laravel_postgres
#     environment:
      # POSTGRES_DB: laravel_app
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     networks:
#       - laravel_network

#   # Laravel Backend
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: laravel_backend
#     volumes:
#       - ./backend:/var/www
#       - /var/www/vendor
#     depends_on:
#       - postgres
#     networks:
#       - laravel_network

#   # Nginx for Laravel
#   nginx:
#     image: nginx:alpine
#     container_name: laravel_nginx
#     ports:
#       - "8000:80"
#     volumes:
#       - ./backend:/var/www
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - backend
#     networks:
#       - laravel_network

#   # React Frontend
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: laravel_frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     depends_on:
#       - backend
#     networks:
#       - laravel_network

# volumes:
#   postgres_data:

# networks:
#   laravel_network:
#     driver: bridge

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: pentest_postgres
    environment:
      POSTGRES_DB: laravel_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pentest_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pentest_backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
    networks:
      - pentest_network
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel_app
      DB_USERNAME: postgres
      DB_PASSWORD: password

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pentest_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - pentest_network

  # Caddy Reverse Proxy (HTTPS)
  caddy:
    image: caddy:2-alpine
    container_name: pentest_caddy
    depends_on:
      - backend
      - frontend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./localhost.pem:/localhost.pem
      - ./localhost-key.pem:/localhost-key.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pentest_network

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  pentest_network:
    driver: bridge